name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Nuxt.jsに適したNode.jsのバージョン
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
        working-directory: ./qrfront

      - name: Build
        run: yarn build
        working-directory: ./qrfront

      - name: Generate Static Files
        run: yarn generate
        working-directory: ./qrfront

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./qrfront/dist
